
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

logger:
  default: info
  logs:
    custom_components.eko_karta_zagreb: debug

sensor:
  - platform: eko_karta_zagreb
    name: EkoZG Maksimir
    # station_id: 969
    # lon: 16.01
    # lat: 45.82
    monitored_conditions:
      - temperature
      - pressure
      - humidity
      - air_quality_index
      - carbon_monoxide
      - nitrogen_monoxide
      - nitrogen_dioxide
      - ozone
      - particulate_matter_0_1
      - particulate_matter_10
      - particulate_matter_2_5
      - sulphur_dioxide

weather:
  - platform: eko_karta_zagreb
    name: EkoZG Maksimir
    # station_id: 969
    # lon: 16.01
    # lat: 45.82

air_quality:
  - platform: eko_karta_zagreb
    name: EkoZg Maksimir
    # station_id: 969
    # lon: 16.01
    # lat: 45.82
